### ISSUE TITLE
Getopt uses deprecated function String.lowercase

### ISSUE THREAD

**Issue by ramsdell** [gildor478/ocaml-getopt#2]
Getopt does not compile with ocamlc version 5.1.0.  It appears to be using the deprecated function String.lowercase.  Please patch this as the chase packages makes use of this library.

John

```
[ERROR] The compilation of getopt.20120615 failed at "ocaml setup.ml -configure
        --prefix /Users/ramsdell/.opam/ocaml.5.1.0".
∗ installed dune.3.6.1

#=== ERROR while compiling getopt.20120615 ====================================#
# context     2.1.3 | macos/x86_64 | ocaml.5.1.0 | https://opam.ocaml.org#d9307541
# path        ~/.opam/ocaml.5.1.0/.opam-switch/build/getopt.20120615
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -configure --prefix /Users/ramsdell/.opam/ocaml.5.1.0
# exit-code   2
# env-file    ~/.opam/log/getopt-60059-878a9e.env
# output-file ~/.opam/log/getopt-60059-878a9e.out
### output ###
# File "/home/pveber/usr/ocamlbrew/ocaml-3.12.1/build/odb/install-oasis/oasis-0.3.0~rc3/src/oasis/OASISUtils.ml", line 46, characters 20-36:
# Error: Unbound value String.lowercase
```

**Comment by gildor478** [comment]
Migrated to dune in scemama/ocaml-getopt
